apiVersion: batch/v1
kind: Job
metadata:
  name: job-unziptrain
spec:
  template:
    spec:
      containers:
      - name: cls-container
        image: ubuntu
        command:
          - sh
          - -c
          - |
            apt update && \
            apt install -y python3 python3-pip && \
            apt install unzip && \
            cd /project/data/v2xset && \
            unzip -nv train.zip && \
            echo '===========Commands executed successfully.==========' && \
            sleep 3600
        volumeMounts:
        - name: data
          mountPath: /project
        - name: dshm
          mountPath: /dev/shm
        resources:
          limits:
            ephemeral-storage: "500Gi"
            memory: 200Gi
            cpu: "20"
            # nvidia.com/a100: 4
          requests:
            ephemeral-storage: "500Gi"
            memory: 200Gi
            cpu: "20"
            # nvidia.com/a100: 4
        securityContext:
          runAsUser: 0
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: data
        persistentVolumeClaim:
          claimName: cooppercpvc
      restartPolicy: Never
  backoffLimit: 2
