apiVersion: batch/v1
kind: Job
metadata:
  name: job-trainv2xvit
spec:
  template:
    spec:
      containers:
      - name: cls-container
        image: ubuntu
        command:
          - sh
          - -c
          - |
            apt update && \
            apt install -y tar wget build-essential zlib1g-dev libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev libgdbm-dev libdb5.3-dev libbz2-dev libexpat1-dev liblzma-dev libffi-dev tk-dev software-properties-common libssl-dev && \
            apt -y upgrade && \
            wget https://www.python.org/ftp/python/3.7.11/Python-3.7.11.tgz && \
            tar -xf Python-3.7.11.tgz && \
            cd Python-3.7.11 && \
            ./configure --enable-optimizations --with-ssl && \
            make -j $(nproc) && \
            make altinstall && \
            rm -rf /usr/lib/python3.12/EXTERNALLY-MANAGED && \
            # apt -y install update-alternatives && \
            update-alternatives --install /usr/bin/python python /usr/local/bin/python3.7 1 && \
            update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.7 1 && \
            export PATH=$PATH:/usr/local/bin && \
            cd /project/OpenCOOD && \
            pip3.7 install -r requirements.txt && \
            pip3.7 uninstall -y setuptools && \
            pip3.7 install setuptools && \
            python3.7 setup.py develop && \
            pip3.7 install spconv-cu113 && \
            python3.7 opencood/utils/setup.py build_ext --inplace && \
            apt install -y libgl1-mesa-dri libgl1 && \
            #### Upto this point, it worked from interactive terminal and executed code at least upto the point of searching for training data. 
            #### TODO : Install Pytorch
            #### TODO : train opencood/v2xvit with the dataset
            echo '===========Commands executed successfully.==========' && \
            sleep 3600
        volumeMounts:
        - name: data
          mountPath: /project
        - name: dshm
          mountPath: /dev/shm
        resources:
          limits:
            ephemeral-storage: "500Gi"
            memory: 100Gi
            cpu: "10"
            nvidia.com/gpu: 2
          requests:
            ephemeral-storage: "500Gi"
            memory: 100Gi
            cpu: "10"
            nvidia.com/gpu: 2
        securityContext:
          runAsUser: 0
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: data
        persistentVolumeClaim:
          claimName: cooppercpvc
      restartPolicy: Never
  backoffLimit: 2
